name: Deploy to Firebase - deploy prod on push

on:
  push:
    branches: [main, dev]
    
jobs:
  build_and_preview_prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps and copy .env
      run: |
        yarn install
        yarn build
				echo "${{ secrets.ENV_FILE }}" > ./.env
    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live
