name: Deploy to Firebase - preview on PR

on:
  pull_request:
    branches: [main, dev]
    
jobs:
  build_and_preview_prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        yarn install
        yarn build
    - name: Deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        expires: 7d
			env:
				REACT_APP_FIREBASE_FIRESTORE_DATABASE_URL: "${{ secrets.REACT_APP_FIREBASE_FIRESTORE_DATABASE_URL }}"
				REACT_APP_FIREBASE_API_KEY: "${{ secrets.REACT_APP_FIREBASE_API_KEY }}"
				REACT_APP_FIREBASE_AUTH_DOMAIN: "${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}"
				REACT_APP_FIREBASE_PROJECT_ID: "${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}"
				REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}"
				REACT_APP_FIREBASE_APP_ID: "${{ secrets.REACT_APP_FIREBASE_APP_ID }}"
				REACT_APP_CEREMONY_ID: "${{ secrets.REACT_APP_CEREMONY_ID }}"
				REACT_APP_CEREMONY_BUCKET: "${{ secrets.REACT_APP_CEREMONY_BUCKET }}"
				REACT_APP_AWS_REGION: "${{ secrets.REACT_APP_AWS_REGION }}"
    
