name: Deploy to Firebase hosting - prod

# Controls when the action will run
on:
	push:
		branches: [main, dev]

jobs:
	build_and_preview_prod:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v3
		- name: Install dependencies
			- run: yarn && yarn build
		- name: Deploy
			- uses: FirebaseExtended/action-hosting-deploy@v0
				with:
					repoToken: "${{ secrets.GITHUB_TOKEN }}"
					firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
					channelId: live