name: Deploy to Firebase hosting - preview on PR

# Controls when the action will run
on:
	pull_request:
		branches: [main, dev, feat/firebasehosting]

jobs:
	build_and_preview:
		runs-on: ubuntu-latest
		steps:
		- uses: actions/checkout@v3
		# Add any build steps here.
		- run: npm i && npm run build
		- uses: FirebaseExtended/action-hosting-deploy@v0
			with:
				repoToken: "${{ secrets.GITHUB_TOKEN }}"
				firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
				expires: 7d 
			env:
			FIREBASE_CLI_PREVIEWS: hostingchannels